services:
  mongo:
    image: mongo

  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node app.js"
    depends_on:
      - mongo

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
